sudo: required

language: ruby

services:
  - docker

script:
- docker build . -t krangan/todo-app

after_success:
 - docker login -u $DOCKER_USER -p $DOCKER_PASS
 - docker push krangan/todo-app:latest
 - docker tag todo-app:latest 786833643927.dkr.ecr.us-east-1.amazonaws.com/todo-app:latest
 - docker push 786833643927.dkr.ecr.us-east-1.amazonaws.com/todo-app:latest

